### ISSUE TITLE
Error on MacOS loading docker image due to linux kernal assertion

### ISSUE THREAD

**Issue by AcostaJoshua** [input-output-hk/jormungandr-nix#11]
When calling the `docker load < $(nix-build -A docker-images.jormungandr-standalone --no-link)` on MacOS, an error is encountered on building the _5llsjg6z38k56m1xkh79xj95ap65kz2z-jormungandr-demo.drv_ derivation.

Specifically, the error occurs as a result of a failed assertion on line 53 of the file _1m9lv92hw638gn000v0c9sz994x9wl9k-source/pkgs/os-specific/linux/kernel/generic.nix_, which is used to build the derivation. The line of code causing issue is: `assert stdenv.isLinux;`

At this time, I don't believe MacOS can natively interpret this assertion. As a result, the build of _5llsjg6z38k56m1xkh79xj95ap65kz2z-jormungandr-demo.drv_ cannot be built and a docker image cannot be created on MacOS.

**Comment by disassembler** [comment]
yes, that won't work. You need a linux builder to build the image on. We're planning on setting up CI to build docker containers on every commit in the near future you can import.
