### ISSUE TITLE
nix

### ISSUE THREAD

**Issue by pjweder** [input-output-hk/jormungandr-nix#12]
Hi,

I'm not sure I'm doing this right:

I installed nix:
_$ curl https://nixos.org/nix/install | sh_

Got the repo:
_$ git clone https://github.com/input-output-hk/jormungandr-nix.git_

And tried to build the docker-comtainer:
_$ nix-build -A docker-images.jormungandr-standalone --no-link_

these derivations will be built:
  /nix/store/r94znrfapr3z053y894zrp060bq4n87h-docker-layer-jormungandr-standalone.drv
  /nix/store/rvxyy81prsy94gr4a958ybm4f9kn9dsm-runtime-deps.drv
  /nix/store/chicam9alvdd9bpbfjc43sg6wp6as6pw-docker-image-jormungandr-standalone.tar.gz.drv
**error:** a 'x86_64-linux' with features {kvm} is required to build '/nix/store/r94znrfapr3z053y894zrp060bq4n87h-docker-layer-jormungandr-standalone.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}

Did I miss anything? I'm new to nix. Seems to me feature {kvm} is missing, but i did not found anything on how to add that.

Here my System Infos:
_Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux_

_$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
stepping	: 4
microcode	: 0x200005e
cpu MHz		: 2194.942
cache size	: 14080 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt clwb xsaveopt xsavec xgetbv1 xsaves pku ospke flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
bogomips	: 4389.87
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:_

**Comment by disassembler** [comment]
You may need to enable virtualization in your bios. I don't see vmx in your features

**Comment by pjweder** [comment]
Sorry for that, I had to contact my Hoster first through Costumer Support. Turns out, they don't support that Feature. I'll try nix later. You can close the issue for now. Thank you.
