### ISSUE TITLE
Error build failed

### ISSUE THREAD

**Issue by NotToFly** [input-output-hk/jormungandr-nix#17]
![20-Jul-19 2-45-51 PM](https://user-images.githubusercontent.com/53143161/61590912-38b10180-abb7-11e9-918c-658dac759a53.jpg)

Any suggestions?

**Comment by rinor** [comment]
Try setting up the IOHK binary cache.

**Comment by NotToFly** [comment]
Thanks. It worked. 
Does running node generate log file I can tail? I can't find.

**Comment by disassembler** [comment]
This is 0.2.3 you're building. Please check changes to README.md to grab master tarball.
