### ISSUE TITLE
./faucet-send-money.sh DESTINATION_ADDRESS AMOUNT gives error between two faucets

### ISSUE THREAD

**Issue by markvq** [input-output-hk/jormungandr-nix#18]
I run the latest jormungandr v0.3.1 from an Ubuntu 16.04 LTS OS 

nix-shell --arg faucetAmounts "[ 100000 1234444 34556 ]" --arg numberOfStakePools 2 --argstr logger_output gelf --argstr storage "/tmp/jormungandr-storage" https://github.com/input-output-hk/jormungandr-nix/archive/master.tar.gz

##############################################################################

* CLI version: 0.3.1
* NODE version: 0.3.1

########################################################

* Consensus: genesis_praos
* REST Port: 127.0.0.1:8443
* Slot duration: 10
* block-0 hash: 4513584989bd77c89677258c2259640f6aae0725759e8dfe7b1dfbf030082fcd

########################################################

 Faucet account 1: ca1s4pd9qsqrngpyd7km37rppft4g38n98yakhcht85c8jtatf3380eq7a9xmy
  * public:  ed25519_pk1gtfgyqqu6qfr04ku0scg22a2yfuefe8d4796eaxpujl26vvfm7gqfavds5
  * secret:  ed25519e_sk1xzax5jhfdez07e2qxnkwz8t9hy6wmvcfmq4jwp0xhwd4v55sqetl96c6a08845yfl4hya68mvtfmvucq06gp6suelfg4gg5uzxqj2lqneyxkh
  * amount:  100000
  * pool id: 2dca3b9a19e1909621e6821bcadd5b496e5025b9e6b864d4eb5b3c5716b4f59a

 Faucet account 2: ca1shhff68hkehtfjdtu5qzlzu0schzraw76eekq5w5t3v64xzvdzwcjlz2h8y
  * public:  ed25519_pk1a62w3aakd66vn2l9qqhchrux9cslthkkwds9r4zutx4fsnrgnkysjygfzf
  * secret:  ed25519e_sk1eqzr3e0tvtnut235ytqc0dardsy3vjagwsg0a404tg5jz5rlu3ggxna62422w3prp0tkvvxmnlzd024c75h0zdxmudh6l93s903w8rg2ac080
  * amount:  1234444
  * pool id: f76e63335754d4bbc76438e1e9ae5353c5528af33542d6dee09e6f55cfdafaf5

 Faucet account 3: ca1s40q8akfgjqwmw4fncj9efjnumu8stywp67zd4fnpkllgkheqzgzse8qdg5
  * public:  ed25519_pk1tcpldj2ysrkm42v7y3w2v5lxlpuzerswhsnd2vcdhl6947gqjq5q032uce
  * secret:  ed25519e_sk1jzfglurj09wstv5kkauyvw206g98lejac75c9wq077nw8qyhcprhyppl7elf5hnx40qc6ufhj2jw6r97vl3cpm99tumvh8zawjrhctckjg3cy
  * amount:  34556

##############################################################################

Now I try to transfer 44 tokens to faucet account 3, this gives an error 
 ./faucet-send-money.sh ca1s40q8akfgjqwmw4fncj9efjnumu8stywp67zd4fnpkllgkheqzgzse8qdg5 44
## Sending 44 to ca1s40q8akfgjqwmw4fncj9efjnumu8stywp67zd4fnpkllgkheqzgzse8qdg5
discrimination: testing
account: ed25519_pk1tcpldj2ysrkm42v7y3w2v5lxlpuzerswhsnd2vcdhl6947gqjq5q032uce
node rejected request because of invalid parameters
  |-> **_http://127.0.0.1:8443/v0/account/42d282001cd01237d6dc7c30852baa227994e4edaf8bacf4c1e4bead3189df90: Client Error: 404 Not Found
error: Invalid value for '--account-spending-counter <account-spending-counter>': cannot parse integer from empty string_**

It seems that in the api suffix is missing in the URL http://127.0.0.1:8443/v0/account/42d282001cd01237d6dc7c30852baa227994e4edaf8bacf4c1e4bead3189df90

According to me it should be 
http://127.0.0.1:8443/api/v0/account/42d282001cd01237d6dc7c30852baa227994e4edaf8bacf4c1e4bead3189df90

Best regards,
Mark

**Comment by disassembler** [comment]
thanks for reporting! This is resolved now.
