### ISSUE TITLE
MacOS X - Fails to run-jormungandr

### ISSUE THREAD

**Issue by psychomb** [input-output-hk/jormungandr-nix#3]
<img width="1243" alt="Screenshot 2019-06-23 at 17 12 28" src="https://user-images.githubusercontent.com/46930715/59978230-97945280-95da-11e9-91c4-106e69ba5a53.png">

Not proficient at all in Nix and I report here a simple run / not working issue.
The way the jormungandr parameters are set seems a bit weird. Why 2 secrets ? Does it explain the fail ?

**Comment by psychomb** [comment]
Also does the same when running the README.md command using the other archive.tar.gz

**Comment by jbgi** [comment]
The issue appears to the use `uuidgen` which is not provided by nixpkgs. The script is the one provided by system, which appear to differ on supported flags on OS X. I think I fixed that in last commit.
Can you try again?

**Comment by psychomb** [comment]
<img width="1182" alt="Screenshot 2019-06-24 at 18 26 42" src="https://user-images.githubusercontent.com/46930715/60035650-a39d1480-96ad-11e9-9a3b-e16ffb1276e4.png">

Up and running, many thanks 👍 
One warning  I never got (about one  rejected block) but everything resumes fine.

**Comment by jbgi** [comment]
great, and thanks for the report!
If you find any non-nix related issue please report at https://github.com/input-output-hk/shelley-testnet/issues
