### ISSUE TITLE
Stuck on starting server.

### ISSUE THREAD

**Issue by NotToFly** [input-output-hk/jormungandr-nix#36]
Ubuntu 18.04 on AWS. All ports are open to all traffic.

Describe the bug
Not receiving blocks.

To Reproduce
Start Jurmungandr-nix 0.5.5 with
nix-shell https://github.com/input-output-hk/jormungandr-nix/archive/master.tar.gz  -A shells.testnet -- argst logger_output gelf

![Screenshot_20191004-190500](https://user-images.githubusercontent.com/53143161/66231341-35211700-e6de-11e9-9283-0158ef28c11c.png)

Node is running. No blocks received.

**Comment by disassembler** [comment]
Please open an issue on the support portal. Issues here are specifically about building and running the scripts in this repo. Thanks! https://iohk.zendesk.com/hc/en-us/articles/360036886733-Shelley-Networked-Testnet-Home
