### ISSUE TITLE
Error on the Nix startup script for Jormungander on this page

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/jormungandr-nix#5]
The jormungander startup script with args is missing two parts:
1.  -A shell after the command nix-shell
2. a \ after the word gelf

It should look like this:

<img width="518" alt="Screen Shot 2019-06-25 at 7 59 37 PM" src="https://user-images.githubusercontent.com/25856278/60093236-e6312080-9783-11e9-9c86-f20b9536c901.png">

vice

<img width="928" alt="Screen Shot 2019-06-25 at 7 55 37 PM" src="https://user-images.githubusercontent.com/25856278/60093091-89356a80-9783-11e9-83d4-1dd98d17e59e.png">

**Comment by jbgi** [comment]
thanks. Fixed!

**Comment by fkbinvest** [comment]
does not this link need a "master.tar.gs" ?
