### ISSUE TITLE
please request for amend scripts as below 

### ISSUE THREAD

**Issue by altcoiner** [input-output-hk/jormungandr-nix#8]
> nix-shell -A shell --arg faucetAmounts "[ 100000 1234444 34556 ]" \

          --arg numberOfStakePools 2 \
          --argstr logger_output gelf \
          --argstr storage "/tmp/jormungandr-storage" \
          https://github.com/input-output-hk/jormungandr-nix/archive/68168ddb54de32a52b2aeb61f2810cdc84cfc375.tar.gz \
          --run run-jormungandr

   --argstr logger_output gelf 
> --argstr logger_output gelf \

**Comment by jbgi** [comment]
Good catch thanks!
